defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: faceey_development

test:
  <<: *defaults
  database: faceey_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>